[package]
name = "fits-view-rs"
version = "0.1.0"
edition = "2024"

[profile.release]
debug = true

[dependencies]
anyhow = "1.0.104"
bytemuck = "1.24.0"
byteorder = "1.5.0"
clap = { version = "4.5.54", features = ["derive"] }
dioxus = "0.7.3"
eframe = { version = "0.35.0", default-features = true, features = ["wgpu"] }
egui = "0.35.0"
egui-wgpu = "0.35.0"
egui_extras = { version = "0.35.0", features = ["image"] }
egui_plot = "0.36.0"
env_logger = "0.11.11"
error-iter = "0.4.1"
image = "0.25.9"
indexmap = "2.14.0"
log = "0.4.29"
memmap2 = "0.9.11"
pixels = "0.15.0"
pollster = "1.0.1"
thiserror = "2.0.18"
winit = "0.30.12"
winit_input_helper = "0.17.0"
